Repository SWE2024/project, pull requests merged in 2024-02, with the labels that each got.

#3 added setting function
  assets/background_music.mp3
  assets/btnAudio.png
  assets/btnAudioHover.png
  assets/btnBack.png
  assets/btnBackHover.png
  main.py
Labels: bugfix, enhancement

#11 new buttons
  .gitignore
  assets/btnAudio.png
  assets/btnAudioHover.png
  assets/btnBack.png
  assets/btnBackHover.png
  assets/btnExit.png
  assets/btnExitHover.png
  assets/btnPlay.png
  assets/btnPlayHover.png
  main.py
  profiling.py
Labels: bugfix

#12 added quit button
  assets/btnQuit.png
  assets/btnQuitHover.png
  main.py
Labels: enhancement

#14 added countries
  assets/countries/country1.png
  assets/countries/country10.png
  assets/countries/country11.png
  assets/countries/country12.png
  assets/countries/country13.png
  assets/countries/country14.png
  assets/countries/country15.png
  assets/countries/country16.png
  assets/countries/country17.png
  assets/countries/country18.png
  assets/countries/country19.png
  assets/countries/country2.png
  assets/countries/country20.png
  assets/countries/country21.png
  assets/countries/country22.png
  assets/countries/country23.png
  assets/countries/country24.png
  assets/countries/country25.png
  assets/countries/country26.png
  assets/countries/country27.png
  assets/countries/country3.png
  assets/countries/country4.png
  assets/countries/country5.png
  assets/countries/country6.png
  assets/countries/country7.png
  assets/countries/country8.png
  assets/countries/country9.png
  main.py
Labels: enhancement

#15 fullscreen and audio fix
  main.py
Labels: bugfix

#16 New logo
  assets/imgIco.png
Labels: enhancement

#17 added more classes
  assets/imgIco.png
  main.py
Labels: enhancement

#18 scaling bugfix
  main.py
Labels: bugfix

#19 FIXED COLOUR BUG
  main.py
Labels: bug, bugfix, enhancement

#20 performance and created turns
  main.py
Labels: bugfix, enhancement

#22 Map finally works
  another.py
  assets/imgOcean.jpg
  main.py
Labels: bugfix, enhancement

#23 added random territory on start
  main.py
Labels: enhancement

#24 added sound effects
  assets/music/musicConquer.mp3
  assets/music/musicPlay.mp3
  main.py
Labels: enhancement

#26 resize fix
  main.py
Labels: bugfix

#27 rescaling fix
  main.py
Labels: bugfix

#30 country selection logic bugfix
  another.py
  main.py
Labels: bugfix

#31 finally handled erroneous click
  main.py
Labels: bugfix

#33 networking experiment
  client.py
  graphs.py
  ip.py
  joiner.py
  main.py
  server.py
  starter.py
Labels: enhancement

#34 lower performance hit by using lower resolution images
  assets/countries/map1/country1.png
  assets/countries/map1/country10.png
  assets/countries/map1/country11.png
  assets/countries/map1/country12.png
  assets/countries/map1/country13.png
  assets/countries/map1/country14.png
  assets/countries/map1/country15.png
  assets/countries/map1/country16.png
  assets/countries/map1/country17.png
  assets/countries/map1/country18.png
  assets/countries/map1/country19.png
  assets/countries/map1/country2.png
  assets/countries/map1/country20.png
  assets/countries/map1/country21.png
  assets/countries/map1/country22.png
  assets/countries/map1/country23.png
  assets/countries/map1/country24.png
  assets/countries/map1/country25.png
  assets/countries/map1/country26.png
  assets/countries/map1/country27.png
  assets/countries/map1/country28.png
  assets/countries/map1/country29.png
  assets/countries/map1/country3.png
  assets/countries/map1/country30.png
  assets/countries/map1/country31.png
  assets/countries/map1/country32.png
  assets/countries/map1/country33.png
  assets/countries/map1/country34.png
  assets/countries/map1/country35.png
  assets/countries/map1/country36.png
  assets/countries/map1/country37.png
  assets/countries/map1/country38.png
  assets/countries/map1/country39.png
  assets/countries/map1/country4.png
  assets/countries/map1/country40.png
  assets/countries/map1/country41.png
  assets/countries/map1/country42.png
  assets/countries/map1/country43.png
  assets/countries/map1/country44.png
  assets/countries/map1/country5.png
  assets/countries/map1/country6.png
  assets/countries/map1/country7.png
  assets/countries/map1/country8.png
  assets/countries/map1/country9.png
  assets/imgOcean.jpg
  globals.py
  joiner.py
  main.py
  refactor.md
Labels: bugfix, enhancement
